# Generated by Django 5.2.8 on 2025-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='type',
            field=models.CharField(choices=[('government', 'Government-Funded'), ('private', 'Private')], default='Government-Funded', max_length=20),
            preserve_default=False,
        ),
    ]
