# Generated by Django 5.2.8 on 2025-12-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='income_bracket',
            field=models.PositiveIntegerField(),
        ),
    ]
